import {
  Activity,
  Award,
  BarChart2,
  BarChart3,
  BookOpen,
  Bookmark,
  Boxes,
  Calendar,
  Clock,
  Cpu,
  Download,
  Filter,
  FolderCog,
  Gamepad2,
  Globe,
  HardDrive,
  Heart,
  Image,
  Info,
  LayoutGrid,
  LayoutList,
  LayoutTemplate,
  List,
  Medal,
  MessageSquare,
  Newspaper,
  PanelLeft,
  PieChart,
  PlayCircle,
  Search,
  ShieldCheck,
  ShoppingBag,
  SlidersHorizontal,
  Sparkles,
  Star,
  Tag,
  Terminal,
  TrendingUp,
  Trophy,
  UserCheck,
  Users,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";
import type { PageWidgetKey } from "../../../context/interfaceLayout";

export const WIDGET_ICON: Record<PageWidgetKey, LucideIcon> = {
  hero: Sparkles,
  kpis: SlidersHorizontal,
  filters: Filter,
  subtabs: LayoutList,
  dashboard: LayoutTemplate,
  // Home
  homeQuickStats: TrendingUp,
  homeContinuePlaying: PlayCircle,
  homeRecentlyAdded: Clock,
  homeQuickLaunch: Zap,
  homeActivity: Activity,
  homeAchievements: Trophy,
  homeFriends: Users,
  homeDownloads: Download,
  homeWishlist: Heart,
  homeDeals: Tag,
  homeNews: Newspaper,
  // Library
  libContinuePlaying: PlayCircle,
  libRecentlyAdded: Clock,
  libToolbar: SlidersHorizontal,
  libFilterChips: Filter,
  libPresets: Bookmark,
  libFilterRail: PanelLeft,
  libGrid: LayoutGrid,
  // Game Detail
  gameHero: Sparkles,
  gameTabs: LayoutList,
  gameQuickStats: SlidersHorizontal,
  gameAbout: Info,
  gameStoryline: BookOpen,
  gameMedia: Image,
  gameSysReq: Cpu,
  gameRelations: Boxes,
  gamePulse: Activity,
  // Game Detail — the individual sidebar cards the detail pages render.
  gameInfoKpi: Info,
  gameSteamFeatures: Gamepad2,
  gameRatings: Star,
  gameTimeToBeat: Clock,
  gameSpecsCard: List,
  gameProtonDb: ShieldCheck,
  gameCrackwatch: ShieldCheck,
  gameReleases: Calendar,
  gameLanguages: Globe,
  // Store
  storeHeader: ShoppingBag,
  storeFilters: Filter,
  storeToolbar: SlidersHorizontal,
  storeGrid: LayoutGrid,
  // Wishlist
  wishlistHeader: Heart,
  wishlistToolbar: Search,
  wishlistGrid: LayoutGrid,
  // Deals
  dealsHeader: Tag,
  dealsGrid: LayoutGrid,
  // News
  newsHeader: Newspaper,
  newsToolbar: SlidersHorizontal,
  newsGrid: LayoutGrid,
  // Activity
  activityHeader: Activity,
  activityToolbar: SlidersHorizontal,
  activityKpis: BarChart2,
  activityPersona: UserCheck,
  activityRecords: Medal,
  activityChart: TrendingUp,
  activityInsights: PieChart,
  activityBacklog: Award,
  activityBreakdown: PieChart,
  // Storage
  storageHeader: HardDrive,
  storageHero: PieChart,
  storageControls: SlidersHorizontal,
  storageList: List,
  // Downloads
  downloadsHeader: Download,
  downloadsHero: Activity,
  downloadsSparkline: TrendingUp,
  downloadsFilter: Filter,
  downloadsQueue: List,
  // Achievements
  achievementsHeader: Trophy,
  achievementsHero: Award,
  achievementsCharts: BarChart3,
  achievementsSourceBreakdown: PieChart,
  achievementsShelves: Clock,
  achievementsList: List,
  // Friends
  friendsHeader: Users,
  friendsHero: BarChart2,
  friendsTabs: MessageSquare,
  // Emulators
  emuHeader: Gamepad2,
  emuStats: BarChart2,
  emuSidebar: PanelLeft,
  emuDetail: Terminal,
  // Mods
  modsHeader: Boxes,
  modsCockpit: SlidersHorizontal,
  modsRail: PanelLeft,
  modsWorkspace: FolderCog,
  // Community
  communityHeader: Users,
  communityTabs: LayoutList,
  communityContent: LayoutTemplate,
};

export const WIDGET_KEY_BY_ITEM: Record<string, PageWidgetKey> = {
  widgetKpis: "kpis",
  widgetFilters: "filters",
  widgetSubtabs: "subtabs",
  widgetHero: "hero",
  widgetDashboard: "dashboard",
};
